export default {
   VIEW_ROLES: 'VIEW_ROLES',
   VIEW_MODULES: 'VIEW_MODULES',
   VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',
   VIEW_USERS: 'VIEW_USERS',
   VIEW_DEPARTMENTS: 'VIEW_DEPARTMENTS',
   VIEW_FLOWS: 'VIEW_FLOWS'
}