export default {
   VIEW_ROLES: 'VIEW_ROLES',
   VIEW_MODULES: 'VIEW_MODULES',
   VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',
   VIEW_USERS: 'VIEW_USERS',
   VIEW_DEPARTMENTS: 'VIEW_DEPARTMENTS',
   VIEW_FLOWS: 'VIEW_FLOWS',

   VIEW_STEPS: 'VIEW_STEPS',
   VIEW_OUT_GOING_DOCS: 'VIEW_OUT_GOING_DOCS',
   VIEW_IN_COMING_DOCS: 'VIEW_IN_COMING_DOCS',
   VIEW_STATUSES: 'VIEW_STATUSES'
}
